spring:
  application:
    name: jchatmind
  datasource:
    url: jdbc:postgresql://localhost:5432/jchatmind
    username: postgres
    password: 22374493
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 1255354811@qq.com
    password: lcmxzroxakrngbeg # 邮箱授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  ai:
    deepseek:
      api-key: sk-9eaf7d9714de462f8d9c23430dfe25e1
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    zhipuai:
      api-key: 24cd783a283541c3a01e364a368ed997.AHTaMTMeUVycz4CG
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: glm-4.6
mybatis:
  type-aliases-package: com.kama.jchatmind.model.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.kama.jchatmind.typehandler

document:
  storage:
    base-path: ./data/documents

jchatmind:
  skill:
    enabled: true
    scan-directories:
      - ./skills
    type: OPTIONAL
  rag:
    hybrid:
      enabled: true
      vector-top-k: 20
      bm25-top-k: 20
      final-top-n: 3
      rrf-k: 60
      warmup-on-startup: false
      bm25:
        k1: 1.2
        b: 0.75
